apiVersion: v1
kind: Service
metadata:
  name: kube-tp1-nginx-service
  labels:
    app: kube-tp1
    component: backend
    resource: nginx
spec:
  selector:
    app: kube-tp1
    component: backend
    resource: nginx
  ports:
    - port: 8084
      targetPort: 80
  type: LoadBalancer
