apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-env
data:
  NGINX_PORT: "80" #correspond au port dans le fichier de config nginx.conf
  PROXY_URL: http://kube-tp1-node-service:3000 #correspond au nom du service Node sur le port 3000

