apiVersion: v1
kind: Service
metadata:
  name: kube-tp1-node-service
  labels:
    app: kube-tp1
    component: backend
    resource: node
spec:
  selector:
    app: kube-tp1
    component: backend
    resource: node
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
