apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld
    component: nginx
    resource: backend
spec:
  selector:
    app: helloworld
    component: nginx
    resource: backend
  ports:
    - port: 8083
      targetPort: 3003
  type: LoadBalancer
