apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
    component: nginx
    resource: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
      component: nginx
      resource: backend
  template:
    metadata:
      labels:
        app: helloworld
        component: nginx
        resource: backend
    spec:
      containers:
        - name: backend
          image: kmarques/demo-node
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: helloworld-configmap-env
                  key: PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: helloworld-secret-env
                  key: DATABASE_URL
          ports:
            - containerPort: 3003
